const phrases = [
    "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.",
    "La vita è ciò che ti succede mentre stai facendo altri progetti.",
    "Non è mai troppo tardi per essere ciò che avresti potuto essere.",
    "La felicità è una direzione, non una destinazione.",
    "Il segreto della felicità è la libertà, il segreto della libertà è il coraggio.",
    "Non importa quanto lento tu vada, purché non ti fermi.",
    "Ogni giorno è un nuovo inizio.",
    "Sii il cambiamento che vuoi vedere nel mondo.",
    "La vita è una serie di momenti, goditeli tutti.",
    "La speranza è il sogno del risveglio.",
    "Il modo migliore per prevedere il futuro è crearlo.",
    "Ogni sogno inizia con un sognatore. Ricorda sempre che hai dentro di te la forza, la pazienza e la passione per raggiungere le stelle per cambiare il mondo.",
    "L'unico modo per fare un grande lavoro è amare quello che fai.",
    "Il successo non è la chiave della felicità. La felicità è la chiave del successo. Se ami quello che stai facendo, avrai successo.",
    "Ogni giorno è una seconda possibilità.",
    "La vita è troppo breve per sprecarla a inseguire i sogni di qualcun altro.",
    "La felicità non è qualcosa che arriva postuma, arriva mentre stai vivendo.",
    "L'unica limitazione è la tua immaginazione.",
    "Ogni sogno inizia con un sognatore.",
    "La forza non proviene da ciò che fai. Viene da superare ciò che una volta hai pensato di non poter fare.",
    "Non aspettare. Il momento giusto è adesso.",
    "Non smettere mai di sognare.",
    "La vita è fatta di momenti speciali, rendili indimenticabili.",
    "Sii grato per ciò che hai e lavora per ciò che vuoi.",
    "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.",
    "Le sfide sono ciò che rendono la vita interessante. Superali e diventi più forte.",
    "La vita è troppo breve per rimpiangere ieri, goditi oggi e guarda al domani.",
    "Ogni giorno è un'opportunità per creare un ricordo che durerà per sempre.",
    "Fai ogni giorno qualcosa che ti spaventa.",
    "Non preoccuparti di fallire. Preoccupati di non provare.",
    "La felicità è una scelta, non una conseguenza.",
    "Sii il cambiamento che vuoi vedere nel mondo.",
    "Credi in te stesso e sarai invincibile.",
    "Non c'è elevatore per il successo, devi prendere le scale.",
    "Il successo arriva a coloro che sono troppo occupati a cercarlo.",
    "Le tue uniche limitazioni sono quelle che metti su te stesso.",
    "La tua unica limitazione è la tua immaginazione.",
    "Non aspettare. Il momento giusto è adesso.",
    "Il successo non è definito dal fallimento, ma da come ti rialzi dopo aver fallito.",
    "Non lasciare che il rumore delle opinioni degli altri soffochi la tua voce interiore.",
    "Il momento è tutto. Fai ora.",
    "La vita è come una fotocamera. Focalizzati solo sulle cose importanti, cattura i bei momenti, sviluppa da negativi e se le cose non funzionano, prova di nuovo.",
    "La vita è come una bicicletta. Per mantenere l'equilibrio, devi continuare a muoverti.",
    "Ogni giorno è una nuova opportunità per essere la tua migliore versione di te stesso.",
    "Non guardare indietro con rimpianto, guardare avanti con speranza.",
    "Il segreto del cambiamento è concentrare tutta la tua energia non per combattere il vecchio, ma per costruire il nuovo.",
    "Non importa quanto sia lento il progresso, ciò che conta è che stai avanzando.",
    "Fai ciò che puoi, con quello che hai, dove sei.",
    "Se vuoi qualcosa che non hai mai avuto, devi essere disposto a fare qualcosa che non hai mai fatto.",
    "Il successo non è la chiave della felicità. La felicità è la chiave del successo.",
    "La vita non è trovare te stesso. La vita è creare te stesso.",
    "Il segreto è non guardare indietro. Devi solo preoccuparti di dove stai andando.",
    "Una volta che scegli la speranza, qualsiasi cosa diventi possibile.",
    "Non importa quanto sia difficile il passato, puoi sempre avere un nuovo inizio.",
    "Se vuoi fare una cosa,"
];
module.exports = phrases;
